services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirasa-service
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - sirasa-network
    restart: always
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - sirasa-network
    restart: always
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "6379"

networks:
  sirasa-network:
    driver: bridge
