services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirasa-service
    ports:
      - "3000"
    depends_on:
      - redis
    networks:
      - sirasa-network
    restart: always
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - sirasa-network
    restart: always
    ports:
      - "6379"

networks:
  sirasa-network:
    driver: bridge
