name: CI/CD for Sirasa Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy & Restart Containers via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Memeriksa & Membuat Network..."
            docker network inspect sirasa-network >/dev/null 2>&1 || docker network create sirasa-network

            echo "Menarik Perubahan Terbaru..."
            cd /root/app/SIRASA-Service && git pull origin main

            echo "Membuat folder public..."
            mkdir -p /root/app/SIRASA-Service/public
            sudo chown -R 1000:1000 /root/app/SIRASA-Service/public

            echo "Menjaga Volume uploads dan logs tetap ada..."
            docker volume inspect uploads-data >/dev/null 2>&1 || docker volume create uploads-data
            docker volume inspect logs-data >/dev/null 2>&1 || docker volume create logs-data

            echo "Membangun ulang service tanpa menghentikan database..."
            docker compose up -d --no-deps --build app

            echo "Menyalin data uploads dan logs ke luar container..."
            docker cp sirasa-service:/app/uploads /root/app/SIRASA-Service/
            docker cp sirasa-service:/app/logs /root/app/SIRASA-Service/

            echo "Mengatur izin folder uploads dan logs..."
            sudo chown -R 1000:1000 /root/app/SIRASA-Service/uploads
            sudo chown -R 1000:1000 /root/app/SIRASA-Service/logs
