name: CI/CD for Sirasa Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Logout from Docker Hub (Prevent Auth Issues)
        run: docker logout || true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/sirasa-service .
          docker push ${{ vars.DOCKER_USERNAME }}/sirasa-service

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy & Restart Container via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Login ke Docker Hub..."
            docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "Memeriksa & Membuat Network..."
            docker network inspect sirasa-network >/dev/null 2>&1 || docker network create sirasa-network

            echo "Pull Image..."
            docker pull ${{ vars.DOCKER_USERNAME }}/sirasa-service

            echo "Menghentikan Container Lama..."
            docker stop sirasa-service || true
            docker rm sirasa-service || true

            echo "Menjalankan Container Baru..."
            docker run -d --pull=always --name sirasa-service -p 3000:3000 \
              --network sirasa-network \
              --env-file /sirasa/dev/SIRASA-Service/.env \
              ${{ vars.DOCKER_USERNAME }}/sirasa-service

