name: CI/CD for Sirasa Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy & Restart Containers via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Memeriksa & Membuat Network..."
            docker network inspect sirasa-network >/dev/null 2>&1 || docker network create sirasa-network

            echo "Menarik Perubahan Terbaru..."
            cd /root/sirasa/dev/SIRASA-Service && git pull origin main

            echo "Membangun ulang image"
            docker compose build --parallel

            echo "Restarting Containers yang berubah..."
            docker compose up -d --remove-orphans --no-deps sirasa-service