name: CI/CD for Sirasa Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy & Restart Containers via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Cek & buat Docker network jika belum ada..."
            docker network inspect sirasa-network >/dev/null 2>&1 || docker network create sirasa-network

            echo "Ambil update terbaru dari repository..."
            cd /root/app/SIRASA-Service && git pull origin main

            echo "Buat folder public/uploads/logs jika belum ada..."
            mkdir -p /root/app/SIRASA-Service/public
            mkdir -p /root/app/SIRASA-Service/uploads
            mkdir -p /root/app/SIRASA-Service/logs

            echo "Pastikan permission folder benar..."
            sudo chown -R 1000:1000 /root/app/SIRASA-Service/public
            sudo chown -R 1000:1000 /root/app/SIRASA-Service/uploads
            sudo chown -R 1000:1000 /root/app/SIRASA-Service/logs

            echo "Build dan deploy service tanpa ganggu redis..."
            docker compose -f /root/app/SIRASA-Service/docker-compose.yml up -d --no-deps --build app

            echo "Selesai deploy!"
